[package]
name = "gadgets"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.37"
web-sys = "0.3.14"
js-sys = "0.3.14"
[lib]
crate-type = ["cdylib", "rlib"]
